---
-   hosts: oaisim-enB
    become: yes
    remote_user: root
    vars:
        COPY_RIGHT: 'ciromacedo@gmail.com'
        build_with_dependecies: 'false'
        BASE_DIR_INSTALL_UE : "ansible_ue"
    tasks:

        - name : Remove all old UE implantation
          become: true
          ignore_errors: true
          shell:  |
                sudo rm -rf {{ BASE_DIR_INSTALL_UE }}

        - name : Create UE Directory
          become: true
          shell:  |
                sudo mkdir {{ BASE_DIR_INSTALL_UE }}

        - name  : Install git if not exist
          apt:
            name: git
            state: present
            update_cache: yes

        - name  : Clone openairinterface5g repository - https://gitlab.eurecom.fr/oai/openairinterface5g/
          shell:  git clone --branch v1.0.0 https://gitlab.eurecom.fr/oai/openairinterface5g/ 
          args:
            chdir: "{{ BASE_DIR_INSTALL_UE }}" 

        - name  : Install UE - Remove ue.nfapi.conf file
          shell:  rm openairinterface5g/ci-scripts/conf_files/ue.nfapi.conf 
          args:
            chdir: "{{ BASE_DIR_INSTALL_UE }}" 
        
        - name  : Config UE - Build ue.nfapi.conf file
          copy:
            dest: "{{ BASE_DIR_INSTALL_UE }}/openairinterface5g/ci-scripts/conf_files/ue.nfapi.conf"
            content: |
                log_config = {
                    global_log_level                      ="info";
                    global_log_verbosity                  ="medium";
                    hw_log_level                          ="info";
                    hw_log_verbosity                      ="medium";
                    phy_log_level                         ="info";
                    phy_log_verbosity                     ="medium";
                    mac_log_level                         ="info";
                    mac_log_verbosity                     ="medium";
                    rlc_log_level                         ="info";
                    rlc_log_verbosity                     ="medium";
                    pdcp_log_level                        ="info";
                    pdcp_log_verbosity                    ="medium";
                    rrc_log_level                         ="info";
                    rrc_log_verbosity                     ="full";
                    };


                    L1s = (
                            {
                        num_cc = 1;
                        tr_n_preference = "nfapi";
                            local_n_if_name  = "lo";
                            remote_n_address = "127.0.0.2";
                            local_n_address  = "127.0.0.1";
                            local_n_portc    = 50000;
                            remote_n_portc   = 50001;
                            local_n_portd    = 50010;
                            remote_n_portd   = 50011;
                            }  
                    );

                    RUs = (
                        {		  
                        local_rf       = "yes"
                        nb_tx          = 1
                        nb_rx          = 1
                        att_tx         = 90
                        att_rx         = 0;
                        bands          = [7,38,42,43];
                        max_pdschReferenceSignalPower = -27;
                        max_rxgain                    = 125;
                        }		      
                    );

        - name  : Loopback
          become: true
          shell:  |
                sudo ifconfig lo: 127.0.0.2 netmask 255.0.0.0 up

        - name  : Build UE with dependencies - this step can be lazy, wait
          shell: source oaienv && ./cmake_targets/build_oai --UE  -x -t ETHERNET -c -I --musim
          args:
            chdir: "{{ BASE_DIR_INSTALL_UE }}/openairinterface5g"
            executable: /bin/bash
          when: build_with_dependecies == 'true'
       
        - name  : Build UE without dependencies - this step can be lazy, wait
          shell: source oaienv && ./cmake_targets/build_oai --UE  -x -t ETHERNET -c -I --musim
          args:
            chdir: "{{ BASE_DIR_INSTALL_UE }}/openairinterface5g"
            executable: /bin/bash
          when: build_with_dependecies == 'false'

        - name  : Init NAS UE Layer
          shell: source init_nas_s1 UE
          args:
            chdir: "{{ BASE_DIR_INSTALL_UE }}/openairinterface5g/cmake_targets/tools"
            executable: /bin/bash
