---
-   hosts: free5g-CORE
    become: yes
    remote_user: root
    vars:
        COPY_RIGHT: 'ciromacedo@gmail.com'
        build_with_dependecies: 'false'
        enable_ipv6: 'true'
        run_free5g_backgroud: 'false'
        BASE_DIR_INSTALL : "ansible_free5GC"
    tasks:
        - name : Install Docker-CE
          become: true
          shell:  |
                sudo apt-get remove docker docker-engine docker.io
                sudo apt-get update
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

                sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
                sudo apt-get update
                sudo apt-get install docker-ce -y
