---
-   hosts: free5g-CORE
    become: yes
    remote_user: root
    vars:
        COPY_RIGHT: 'ciromacedo@gmail.com'
        build_with_dependecies: 'false'
        enable_ipv6: 'true'
        BASE_DIR_INSTALL : "ansible_free5GC"
    tasks:
        - fail: 
            msg: "'physical_network_interface' not found, this parameter is required!"
          when: physical_network_interface == ''
       
        - name : Remove all old implantation
          become: true
          ignore_errors: true
          shell:  |
                sudo rm -rf {{ BASE_DIR_INSTALL }}

        - name : Create Install Directory
          become: true
          shell:  |
                sudo mkdir {{ BASE_DIR_INSTALL }}
        
        - name : Install MongoDB 3.6.3
          become: true
          shell:  |
                sudo apt-get update
                sudo apt-get -y install mongodb wget git
                sudo systemctl start mongodb

        - name : Install Golang 1.14.2
          become: true
          shell:  |
                sudo add-apt-repository ppa:longsleep/golang-backports -y
                sudo apt update
                sudo apt install golang-go -y

        - name : Add Golang dependency packages
          become: true
          shell:  |
                go get -u -v "github.com/gorilla/mux"
                go get -u -v "golang.org/x/net/http2"
                go get -u -v "golang.org/x/sys/unix"
        
        - name : Write the configuration file for the TUN device 1/2
          become: true
          shell:  |
                sudo sh -c "cat << EOF > /etc/systemd/network/99-free5gc.netdev
                [NetDev]
                Name=uptun
                Kind=tun
                EOF"
        
        - name : Write the configuration file for the TUN device 2/2
          become: true
          shell:  |
                sudo systemctl enable systemd-networkd
                sudo systemctl restart systemd-networkd
        
        - name : IP address on TUN device. IPV6 Enable
          become: true
          shell:  |
                sudo sh -c "cat << EOF > /etc/systemd/network/99-free5gc.network
                [Match]
                Name=uptun
                [Network]
                Address=45.45.0.1/16
                Address=cafe::1/64
                EOF"
          when:  enable_ipv6 == 'true'
        
        - name : IP address on TUN device. IPV6 Disable 
          become: true
          shell:  |
                sudo sh -c "echo 'net.ipv6.conf.uptun.disable_ipv6=0' > /etc/sysctl.d/30-free5gc.conf"
                sudo sysctl -p /etc/sysctl.d/30-free5gc.conf
          when:  enable_ipv6 == 'false'

        - name : IP address on TUN device. IPV6 Disable 
          become: true
          shell:  |
                sudo sh -c "cat << EOF > /etc/systemd/network/99-free5gc.network
                [Match]
                Name=uptun
                [Network]
                Address=45.45.0.1/16
                EOF"
          when:  enable_ipv6 == 'false'
        
        - name : IP address on TUN device. IPV6 Disable 
          become: true
          shell:  |
                sudo systemctl enable systemd-networkd
                sudo systemctl restart systemd-networkd
                sudo apt-get -y install net-tools

        - name : Install AMF, SMF, UPF, HSS, and PCRF depedencies  
          become: true
          shell:  |
                sudo apt-get -y install autoconf libtool gcc pkg-config git flex bison libsctp-dev libgnutls28-dev libgcrypt-dev libssl-dev libidn11-dev libmongoc-dev libbson-dev libyaml-dev

        - name : Git clone free5GCore 
          shell: git clone https://bitbucket.org/nctu_5g/free5gc-stage-1.git
          args:
            chdir: "{{ BASE_DIR_INSTALL }}"

        - name : Compile free5GCore 
          ignore_errors: true
          shell:  |
                autoreconf -iv
                ./configure --prefix=`pwd`/install
                make -j `nproc`
          args:
            chdir: "{{ BASE_DIR_INSTALL }}/free5gc-stage-1"

        - name : Generate new Certs 
          shell:  |
                ./make_certs.sh . 
          args:
            chdir: "{{ BASE_DIR_INSTALL }}/free5gc-stage-1/support/freeDiameter"

        - name : Run Make Install 
          ignore_errors: true
          shell:  |
                make install
          args:
            chdir: "{{ BASE_DIR_INSTALL }}/free5gc-stage-1"

        - name  : Core Network Configuration - remove free5gc.conf old file
          shell:  rm free5gc-stage-1/install/etc/free5gc/free5gc.conf 
          args:
            chdir: "{{ BASE_DIR_INSTALL }}" 

        - name  : Core Network Configuration - Build free5gc.conf
          copy:
            dest: "{{ BASE_DIR_INSTALL }}/free5gc-stage-1/install/etc/free5gc/free5gc.conf"
            content: |
                db_uri: mongodb://localhost/free5gc

                logger:
                    file: /root/{{ BASE_DIR_INSTALL }}/free5gc-stage-1/install/var/log/free5gc/free5gc.log
                    trace:
                        app: 1
                        s1ap: 1
                        nas: 1
                        diameter: 1
                        gtp: 1
                        pfcp: 1
                        sbi: 1

                #
                # parameter:
                #
                #  o Number of output streams per SCTP associations.
                #      sctp_streams: 30
                #
                #  o Disable use of IPv4 addresses (only IPv6)
                #      no_ipv4: true
                #
                #  o Disable use of IPv6 addresses (only IPv4)
                #      no_ipv6: true
                #
                #  o Prefer IPv4 instead of IPv6 for estabishing new GTP connections.
                #      prefer_ipv4: true
                #
                #  o Enable Multicast traffic to the UE
                #      multicast: true
                #
                #  o Disable Stateless Address Autoconfiguration for IPv6
                #      no_slaac: true
                #                                                                                                                                                                                               #                                                                                                                                                                                               parameter:                                                                                                                                                                                          no_ipv6: true

                amf:
                    freeDiameter: amf.conf
                  
                #
                #  <S1AP Server>>
                #
                #  o S1AP Server(all address avaiable)
                #    s1ap:
                #
                #  o S1AP Server(0.0.0.0:36412)
                #    s1ap:
                #      addr: 0.0.0.0
                #
                #  o S1AP Server(127.0.0.1:36412, [::1]:36412)
                #    s1ap:
                #      - addr: 127.0.0.1
                #      - addr: ::1

                #  o S1AP Server(different port)
                #    s1ap:
                #      - addr: 127.0.0.1
                #        port: 36413
                #
                #  o S1AP Server(address avaiable in `eth0` interface)
                #    s1ap:
                #      dev: eth0
                #
                    s1ap:
                      addr: {{ ansible_default_ipv4.address }}
                #
                #  <GUMMEI>
                #
                #  o Multiple GUMMEI
                #    gummei:
                #      - plmn_id:
                #          mcc: 001
                #          mnc: 01
                #        mme_gid: 2
                #        mme_code: 1
                #      - plmn_id:
                #          - mcc: 002                                                                                                                                                                           #            mnc: 02                                                                                                                                                                            #          - mcc: 003                                                                                                                                                                           #            mnc: 03
                #        mme_gid: [3, 4]
                #        mme_code:
                #          - 2
                #          - 3
                #
                    gummei:
                      plmn_id:
                        mcc: 208
                        mnc: 93
                      mme_gid: 1
                      mme_code: 1

                #
                #  <TAI>
                #
                #  o Multiple TAI
                #    tai:
                #      - plmn_id:
                #          mcc: 001
                #          mnc: 01
                #        tac: [1, 2, 3]
                #    tai:
                #      - plmn_id:
                #          mcc: 002
                #          mnc: 02
                #        tac: 4
                #      - plmn_id:
                #          mcc: 003
                #          mnc: 03
                #        tac: 5
                #    tai:
                #      - plmn_id:
                #          mcc: 004
                #          mnc: 04
                #        tac: [6, 7]
                #      - plmn_id:
                #          mcc: 005
                #          mnc: 05
                #        tac: 8
                #      - plmn_id:
                #          mcc: 006
                #          mnc: 06
                #        tac: [9, 10]
                #
                    tai:
                      plmn_id:
                        mcc: 208
                        mnc: 93
                      tac: 1

                    security:
                        integrity_order : [ EIA1, EIA2, EIA0 ]
                        ciphering_order : [ EEA0, EEA1, EEA2 ]
                #
                #                                                                                                                                                                                               #  <Network Name>
                #    network_name:
                #        full: free5GC
                #        short: free
                #

                    network_name:
                        full: free5GC

                hss:
                    freeDiameter: hss.conf

                pcrf:
                    freeDiameter: pcrf.conf

                smf:
                    freeDiameter: smf.conf

                    pfcp:
                      - addr: 127.0.0.2
                      - addr: ::1

                    upf:
                      - addr: {{ ansible_default_ipv4.address }}                                                                                                                                                                    
                    http:
                      addr: 127.0.0.1
                      port: 8080

                #
                #  <UE Pool>
                #
                #  o IPv4 Pool
                #    $ sudo ip addr add 45.45.0.1/16 dev uptun
                #
                #    ue_pool:
                #      addr: 45.45.0.1/16
                #
                #  o IPv4/IPv6 Pool
                #    $ sudo ip addr add 45.45.0.1/16 dev uptun
                #    $ sudo ip addr add cafe:1::1/64 dev uptun
                #
                #    ue_pool:
                #      - addr: 45.45.0.1/16
                #      - addr: cafe:1::1/64
                #
                #                                                                                                                                                                                               #  o Specific APN(e.g 'volte') uses 45.46.0.1/16, cafe:2::1/64
                #    All other APNs use 45.45.0.1/16, cafe:1::1/64
                #    $ sudo ip addr add 45.45.0.1/16 dev uptun
                #    $ sudo ip addr add 45.46.0.1/16 dev uptun
                #    $ sudo ip addr add cafe:1::1/64 dev uptun
                #    $ sudo ip addr add cafe:2::1/64 dev uptun
                #
                #    ue_pool:
                #      - addr: 45.45.0.1/16
                #      - addr: cafe:1::1/64
                #      - addr: 45.46.0.1/16
                #        apn: volte
                #      - addr: cafe:2::1/64
                #        apn: volte
                #
                #  o Multiple Devices (default: uptun)
                #    $ sudo ip addr add 45.45.0.1/16 dev uptun
                #    $ sudo ip addr add cafe:1::1/64 dev uptun2
                #    $ sudo ip addr add 45.46.0.1/16 dev uptun3
                #    $ sudo ip addr add cafe:2::1/64 dev uptun3
                #
                #
                #    ue_pool:
                #      - addr: 45.45.0.1/16                                                                                                                                                                     #      - addr: cafe:1::1/64
                #        dev: uptun2
                #      - addr: 45.46.0.1/16
                #        apn: volte
                #        dev: uptun3
                #      - addr: cafe:2::1/64
                #        apn: volte
                #        dev: uptun3
                #
                    ue_pool:
                      - addr: 45.45.0.1/16
                      - addr: cafe::1/64

                #
                #  <Domain Name Server>
                #
                #  o Primary/Secondary can be configured. Others are ignored.
                #
                    dns:
                      - 8.8.8.8
                      - 8.8.4.4
                      - 2001:4860:4860::8888
                      - 2001:4860:4860::8844                                                                                                                                                                    
                upf:
                    pfcp:
                      addr:
                        - {{ ansible_default_ipv4.address }}
                        - ::1

                #
                #  <GTP-U Server>>
                #
                #  o GTP-U Server(127.0.0.3:2152, [::1]:2152)
                #    gtpu:
                #      - addr: 127.0.0.3
                #      - addr: ::1
                #
                #  o Same configuration(127.0.0.3:2152, [::1]:2152) as below.
                #    gtpu:
                #      name: localhost
                #
                    gtpu:
                      - addr: {{ ansible_default_ipv4.address }}
                      - addr: ::1

                    ue_pool:
                      - addr: 45.45.0.1/16
                      - addr: cafe::1/64

                    dns:
                      - 8.8.8.8
                      - 8.8.4.4                                                                                                                                                                                       - 2001:4860:4860::8888                                                                                                                                                                          - 2001:4860:4860::8844


        - name : Install Node 
          shell:  |
                sudo apt-get -y install curl
                curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
                sudo apt-get -y install nodejs

        - name : Install Web User Interface 
          ignore_errors: true
          shell:  |
                npm install
          args:
            chdir: "{{ BASE_DIR_INSTALL }}/free5gc-stage-1/webui"