---
-   hosts: oaisim-RAM
    become: yes
    remote_user: root
    vars:
        BASE_DIR_INSTALL_UE : "ansible_ue"
        username_core_web_interface : "admin"
        pass_core_web_interface : "1423"
        user_equiments:
          - { ue_id: UE0 ,   msin: '0000000001' }
          - { ue_id: UE1 ,   msin: '0000000002' }
          - { ue_id: UE2 ,   msin: '0000000003' }
          - { ue_id: UE3 ,   msin: '0000000004' }
          - { ue_id: UE4 ,   msin: '0000000005' }
          - { ue_id: UE5 ,   msin: '0000000006' }
          - { ue_id: UE6 ,   msin: '0000000007' }
          - { ue_id: UE7 ,   msin: '0000000008' }
          - { ue_id: UE8 ,   msin: '0000000009' }
          - { ue_id: UE9 ,   msin: '0000000010' }
          - { ue_id: UE10 ,  msin: '0000000011' }
          - { ue_id: UE11 ,  msin: '0000000012' }
          - { ue_id: UE12 ,  msin: '0000000013' }
          - { ue_id: UE13 ,  msin: '0000000014' }
          - { ue_id: UE14 ,  msin: '0000000015' }
          - { ue_id: UE15 ,  msin: '0000000016' }
          - { ue_id: UE16 ,  msin: '0000000017' }
          - { ue_id: UE17 ,  msin: '0000000018' }
          - { ue_id: UE18 ,  msin: '0000000019' }
          - { ue_id: UE19 ,  msin: '0000000020' }
          - { ue_id: UE20 ,  msin: '0000000021' }
          - { ue_id: UE21 ,  msin: '0000000022' }
          - { ue_id: UE22 ,  msin: '0000000023' }
          - { ue_id: UE23 ,  msin: '0000000024' }
          - { ue_id: UE24 ,  msin: '0000000025' }
          - { ue_id: UE25 ,  msin: '0000000026' }
          - { ue_id: UE26 ,  msin: '0000000027' }
          - { ue_id: UE27 ,  msin: '0000000028' }
          - { ue_id: UE28 ,  msin: '0000000029' }
          - { ue_id: UE29 ,  msin: '0000000030' }
          - { ue_id: UE30 ,  msin: '0000000031' }
          - { ue_id: UE31 ,  msin: '0000000032' }
          - { ue_id: UE32 ,  msin: '0000000033' }
          - { ue_id: UE33 ,  msin: '0000000034' }
          - { ue_id: UE34 ,  msin: '0000000035' }
          - { ue_id: UE35 ,  msin: '0000000036' }
          - { ue_id: UE36 ,  msin: '0000000037' }
          - { ue_id: UE37 ,  msin: '0000000038' }
          - { ue_id: UE38 ,  msin: '0000000039' }
          - { ue_id: UE39 ,  msin: '0000000040' }
          - { ue_id: UE40 ,  msin: '0000000041' }
          - { ue_id: UE41 ,  msin: '0000000042' }
          - { ue_id: UE42 ,  msin: '0000000043' }
          - { ue_id: UE43 ,  msin: '0000000044' }
          - { ue_id: UE44 ,  msin: '0000000045' }
          - { ue_id: UE45 ,  msin: '0000000046' }
          - { ue_id: UE46 ,  msin: '0000000047' }
          - { ue_id: UE47 ,  msin: '0000000048' }
          - { ue_id: UE48 ,  msin: '0000000049' }
          - { ue_id: UE49 ,  msin: '0000000050' }
          - { ue_id: UE50 ,  msin: '0000000051' }
          - { ue_id: UE51 ,  msin: '0000000052' }
          - { ue_id: UE52 ,  msin: '0000000053' }
          - { ue_id: UE53 ,  msin: '0000000054' }
          - { ue_id: UE54 ,  msin: '0000000055' }
          - { ue_id: UE55 ,  msin: '0000000056' }
          - { ue_id: UE56 ,  msin: '0000000057' }
          - { ue_id: UE57 ,  msin: '0000000058' }
          - { ue_id: UE58 ,  msin: '0000000059' }
          - { ue_id: UE59 ,  msin: '0000000060' }
          - { ue_id: UE60 ,  msin: '0000000061' }
          - { ue_id: UE61 ,  msin: '0000000062' }
          - { ue_id: UE62 ,  msin: '0000000063' }
          - { ue_id: UE63 ,  msin: '0000000064' }
          - { ue_id: UE64 ,  msin: '0000000065' }
          - { ue_id: UE65 ,  msin: '0000000066' }
          - { ue_id: UE66 ,  msin: '0000000067' }
          - { ue_id: UE67 ,  msin: '0000000068' }
          - { ue_id: UE68 ,  msin: '0000000069' }
          - { ue_id: UE69 ,  msin: '0000000070' }
          - { ue_id: UE70 ,  msin: '0000000071' }
          - { ue_id: UE71 ,  msin: '0000000072' }
          - { ue_id: UE72 ,  msin: '0000000073' }
          - { ue_id: UE73 ,  msin: '0000000074' }
          - { ue_id: UE74 ,  msin: '0000000075' }
          - { ue_id: UE75 ,  msin: '0000000076' }
          - { ue_id: UE76 ,  msin: '0000000077' }
          - { ue_id: UE77 ,  msin: '0000000078' }
          - { ue_id: UE78 ,  msin: '0000000079' }
          - { ue_id: UE79 ,  msin: '0000000080' }
          - { ue_id: UE80 ,  msin: '0000000081' }
          - { ue_id: UE81 ,  msin: '0000000082' }
          - { ue_id: UE82 ,  msin: '0000000083' }
          - { ue_id: UE83 ,  msin: '0000000084' }
          - { ue_id: UE84 ,  msin: '0000000085' }
          - { ue_id: UE85 ,  msin: '0000000086' }
          - { ue_id: UE86 ,  msin: '0000000087' }
          - { ue_id: UE87 ,  msin: '0000000088' }
          - { ue_id: UE88 ,  msin: '0000000089' }
          - { ue_id: UE89 ,  msin: '0000000090' }
          - { ue_id: UE90 ,  msin: '0000000091' }
          - { ue_id: UE91 ,  msin: '0000000092' }
          - { ue_id: UE92 ,  msin: '0000000093' }
          - { ue_id: UE93 ,  msin: '0000000094' }
          - { ue_id: UE94 ,  msin: '0000000095' }
          - { ue_id: UE95 ,  msin: '0000000096' }
          - { ue_id: UE96 ,  msin: '0000000097' }
          - { ue_id: UE97 ,  msin: '0000000098' }
          - { ue_id: UE98 ,  msin: '0000000099' }
          - { ue_id: UE99 ,  msin: '0000000100' }
    tasks:
        - fail: 
            msg: "'core_installation_ip_address' not found, this parameter is required!"
          when: core_installation_ip_address == ''

        - name: Get CSRF Access Token
          shell: |
              curl "http://{{ core_installation_ip_address }}:3000/api/auth/csrf" -H 'Connection: kee$          
          register: csrf
       
        - name: Login into Core Web Interface
          shell: |
              curl "http://{{ core_installation_ip_address }}:3000/api/auth/login" -H 'Connection: keep-alive' -H 'Accept: application/json, text/plain, */*' -H "X-CSRF-TOKEN: {{ csrf.stdout }}" -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36' -H 'Content-Type: application/json;charset=UTF-8' -H "Origin: http://{{ core_installation_ip_address }}:3000" -H 'Sec-Fetch-Site: same-origin' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Dest: empty' -H 'Accept-Language: en-US,en;q=0.9,pt;q=0.8,pt-BR;q=0.7' -b /tmp/free5gc.txt -o /dev/null --data-binary '{"username":"{{ username_core_web_interface }}","password":"{{ pass_core_web_interface }}"}' --compressed  


#        - name: Add User equipments in RAN file config
#          blockinfile:
#            path: /root/{{ BASE_DIR_INSTALL_UE }}/openairinterface5g/openair3/NAS/TOOLS/ue_eurecom_test_sfr.conf
#            block: |
#                {{ item.ue_id }}:
#                  {
#                      USER: {
#                         IMEI="356113022094149";
#                          MANUFACTURER="EURECOM";
#                          MODEL="LTE Android PC";
#                          PIN="0000";
#                      };
#                      SIM: {
#                          MSIN="{{ item.msin }}";
#                          USIM_API_K="8baf473f2f8fd09487cccbd7097c6862";
#                          OPC="e734f8734007d6c5ce7a0508809e7e9c";
#                          MSISDN="33638020004";
#                      };
#                      HPLMN= "20893";
#                      UCPLMN_LIST = ();
#                      OPLMN_LIST = ("00101", "20810", "20811", "20813", "20893", "310280", "310028");
#                      OCPLMN_LIST = ("22210", "21401", "21406", "26202", "26204");
#                      FPLMN_LIST = ();
#                      EHPLMN_LIST= ();
#                  };
#            marker: "# {mark} User Equipment {{ item.ue_id }}"
#          loop: "{{ user_equiments }}"
#          loop_control:
#            index_var: ue_idx
#          when: "ue_idx|int < {{ num_ues }}"