---
-   hosts: oaisim-RAM
    become: yes
    remote_user: root
    vars:
        COPY_RIGHT: 'ciromacedo@gmail.com'
        build_with_dependecies: 'false'
        core_installation_ip_address: 'REPLACE_THIS_WITH_THE_CORE_INSTALLATION_IP_ADDRESS'
        num_ues: '1'
        HPLMN : "20893"
        USIM_API_K : "8baf473f2f8fd09487cccbd7097c6862"
        OPC : "e734f8734007d6c5ce7a0508809e7e9c"
        username_core_web_interface : "admin"
        pass_core_web_interface : "1423"
        config_vm: 'false'
        BASE_DIR_INSTALL_ENB : "ansible_enB"
        BASE_DIR_INSTALL_UE : "ansible_ue"
        user_equiments:
          - { ue_id: UE0 ,   msin: '0000000001' }
          - { ue_id: UE1 ,   msin: '0000000002' }
          - { ue_id: UE2 ,   msin: '0000000003' }
          - { ue_id: UE3 ,   msin: '0000000004' }
          - { ue_id: UE4 ,   msin: '0000000005' }
          - { ue_id: UE5 ,   msin: '0000000006' }
          - { ue_id: UE6 ,   msin: '0000000007' }
          - { ue_id: UE7 ,   msin: '0000000008' }
          - { ue_id: UE8 ,   msin: '0000000009' }
          - { ue_id: UE9 ,   msin: '0000000010' }
          - { ue_id: UE10 ,  msin: '0000000011' }
          - { ue_id: UE11 ,  msin: '0000000012' }
          - { ue_id: UE12 ,  msin: '0000000013' }
          - { ue_id: UE13 ,  msin: '0000000014' }
          - { ue_id: UE14 ,  msin: '0000000015' }
          - { ue_id: UE15 ,  msin: '0000000016' }
          - { ue_id: UE16 ,  msin: '0000000017' }
          - { ue_id: UE17 ,  msin: '0000000018' }
          - { ue_id: UE18 ,  msin: '0000000019' }
          - { ue_id: UE19 ,  msin: '0000000020' }
          - { ue_id: UE20 ,  msin: '0000000021' }
          - { ue_id: UE21 ,  msin: '0000000022' }
          - { ue_id: UE22 ,  msin: '0000000023' }
          - { ue_id: UE23 ,  msin: '0000000024' }
          - { ue_id: UE24 ,  msin: '0000000025' }
          - { ue_id: UE25 ,  msin: '0000000026' }
          - { ue_id: UE26 ,  msin: '0000000027' }
          - { ue_id: UE27 ,  msin: '0000000028' }
          - { ue_id: UE28 ,  msin: '0000000029' }
          - { ue_id: UE29 ,  msin: '0000000030' }
          - { ue_id: UE30 ,  msin: '0000000031' }
          - { ue_id: UE31 ,  msin: '0000000032' }
          - { ue_id: UE32 ,  msin: '0000000033' }
          - { ue_id: UE33 ,  msin: '0000000034' }
          - { ue_id: UE34 ,  msin: '0000000035' }
          - { ue_id: UE35 ,  msin: '0000000036' }
          - { ue_id: UE36 ,  msin: '0000000037' }
          - { ue_id: UE37 ,  msin: '0000000038' }
          - { ue_id: UE38 ,  msin: '0000000039' }
          - { ue_id: UE39 ,  msin: '0000000040' }
          - { ue_id: UE40 ,  msin: '0000000041' }
          - { ue_id: UE41 ,  msin: '0000000042' }
          - { ue_id: UE42 ,  msin: '0000000043' }
          - { ue_id: UE43 ,  msin: '0000000044' }
          - { ue_id: UE44 ,  msin: '0000000045' }
          - { ue_id: UE45 ,  msin: '0000000046' }
          - { ue_id: UE46 ,  msin: '0000000047' }
          - { ue_id: UE47 ,  msin: '0000000048' }
          - { ue_id: UE48 ,  msin: '0000000049' }
          - { ue_id: UE49 ,  msin: '0000000050' }
          - { ue_id: UE50 ,  msin: '0000000051' }
          - { ue_id: UE51 ,  msin: '0000000052' }
          - { ue_id: UE52 ,  msin: '0000000053' }
          - { ue_id: UE53 ,  msin: '0000000054' }
          - { ue_id: UE54 ,  msin: '0000000055' }
          - { ue_id: UE55 ,  msin: '0000000056' }
          - { ue_id: UE56 ,  msin: '0000000057' }
          - { ue_id: UE57 ,  msin: '0000000058' }
          - { ue_id: UE58 ,  msin: '0000000059' }
          - { ue_id: UE59 ,  msin: '0000000060' }
          - { ue_id: UE60 ,  msin: '0000000061' }
          - { ue_id: UE61 ,  msin: '0000000062' }
          - { ue_id: UE62 ,  msin: '0000000063' }
          - { ue_id: UE63 ,  msin: '0000000064' }
          - { ue_id: UE64 ,  msin: '0000000065' }
          - { ue_id: UE65 ,  msin: '0000000066' }
          - { ue_id: UE66 ,  msin: '0000000067' }
          - { ue_id: UE67 ,  msin: '0000000068' }
          - { ue_id: UE68 ,  msin: '0000000069' }
          - { ue_id: UE69 ,  msin: '0000000070' }
          - { ue_id: UE70 ,  msin: '0000000071' }
          - { ue_id: UE71 ,  msin: '0000000072' }
          - { ue_id: UE72 ,  msin: '0000000073' }
          - { ue_id: UE73 ,  msin: '0000000074' }
          - { ue_id: UE74 ,  msin: '0000000075' }
          - { ue_id: UE75 ,  msin: '0000000076' }
          - { ue_id: UE76 ,  msin: '0000000077' }
          - { ue_id: UE77 ,  msin: '0000000078' }
          - { ue_id: UE78 ,  msin: '0000000079' }
          - { ue_id: UE79 ,  msin: '0000000080' }
          - { ue_id: UE80 ,  msin: '0000000081' }
          - { ue_id: UE81 ,  msin: '0000000082' }
          - { ue_id: UE82 ,  msin: '0000000083' }
          - { ue_id: UE83 ,  msin: '0000000084' }
          - { ue_id: UE84 ,  msin: '0000000085' }
          - { ue_id: UE85 ,  msin: '0000000086' }
          - { ue_id: UE86 ,  msin: '0000000087' }
          - { ue_id: UE87 ,  msin: '0000000088' }
          - { ue_id: UE88 ,  msin: '0000000089' }
          - { ue_id: UE89 ,  msin: '0000000090' }
          - { ue_id: UE90 ,  msin: '0000000091' }
          - { ue_id: UE91 ,  msin: '0000000092' }
          - { ue_id: UE92 ,  msin: '0000000093' }
          - { ue_id: UE93 ,  msin: '0000000094' }
          - { ue_id: UE94 ,  msin: '0000000095' }
          - { ue_id: UE95 ,  msin: '0000000096' }
          - { ue_id: UE96 ,  msin: '0000000097' }
          - { ue_id: UE97 ,  msin: '0000000098' }
          - { ue_id: UE98 ,  msin: '0000000099' }
          - { ue_id: UE99 ,  msin: '0000000100' }
    tasks:
        - name : Remove grub default file
          ignore_errors: true
          shell:  | 
                rm /etc/default/grub 

        - name : Remove blacklist.conf default file
          ignore_errors: true
          shell:  | 
                rm /etc/modprobe.d/blacklist.conf
        
        - name : Remove cpufrequtils default file if exist
          ignore_errors: true
          shell:  | 
                rm /etc/default/cpufrequtils 
        
        - name  : Generate new blacklist.conf file
          copy:
            dest: "/etc/modprobe.d/blacklist.conf"
            content: |
                # This file lists those modules which we don't want to be loaded by
                # alias expansion, usually so some other driver will be loaded for the
                # device instead.

                # evbug is a debug tool that should be loaded explicitly
                blacklist evbug

                # these drivers are very simple, the HID drivers are usually preferred
                blacklist usbmouse
                blacklist usbkbd

                # replaced by e100
                blacklist eepro100

                # replaced by tulip
                blacklist de4x5

                # causes no end of confusion by creating unexpected network interfaces
                blacklist eth1394

                # snd_intel8x0m can interfere with snd_intel8x0, doesn't seem to support much
                # hardware on its own (Ubuntu bug #2011, #6810)
                blacklist snd_intel8x0m

                # Conflicts with dvb driver (which is better for handling this device)
                blacklist snd_aw2

                # Causes trackpads to stop working on Lenovo 11e 2nd gen (Ubuntu: #1802135)
                # and Lenovo x240 to hang on boot (Ubuntu: #1802689)
                blacklist i2c_i801

                # replaced by p54pci
                blacklist prism54

                # replaced by b43 and ssb.
                blacklist bcm43xx

                # most apps now use garmin usb driver directly (Ubuntu: #114565)
                blacklist garmin_gps

                # replaced by asus-laptop (Ubuntu: #184721)
                blacklist asus_acpi

                # low-quality, just noise when being used for sound playback, causes
                # hangs at desktop session start (Ubuntu: #246969)
                blacklist snd_pcsp

                # ugly and loud noise, getting on everyone's nerves; this should be done by a
                # nice pulseaudio bing (Ubuntu: #77010)
                blacklist pcspkr

                # EDAC driver for amd76x clashes with the agp driver preventing the aperture
                # from being initialised (Ubuntu: #297750). Blacklist so that the driver
                # continues to build and is installable for the few cases where its
                # really needed.
                blacklist amd76x_edac

                blacklist intel_powerclamp

        - name  : Generate new grub file
          copy:
            dest: "/etc/default/grub"
            content: |
                # If you change this file, run 'update-grub' afterwards to update
                # /boot/grub/grub.cfg.
                # For full documentation of the options in this file, see:
                #   info -f grub -n 'Simple configuration'

                GRUB_DEFAULT=0
                GRUB_HIDDEN_TIMEOUT=0
                GRUB_HIDDEN_TIMEOUT_QUIET=true
                GRUB_TIMEOUT=10
                GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
                GRUB_CMDLINE_LINUX_DEFAULT="processor.max_cstate=1 intel_idle.max_cstate=0 idle=poll"
                GRUB_CMDLINE_LINUX=""

                # Uncomment to enable BadRAM filtering, modify to suit your needs
                # This works with Linux (no patch required) and with any kernel that obtains
                # the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
                #GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

                # Uncomment to disable graphical terminal (grub-pc only)
                #GRUB_TERMINAL=console

                # The resolution used on graphical terminal
                # note that you can use only modes which your graphic card supports via VBE
                # you can see them in real GRUB with the command `vbeinfo'
                #GRUB_GFXMODE=640x480

                # Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
                #GRUB_DISABLE_LINUX_UUID=true

                # Uncomment to disable generation of recovery mode menu entries
                #GRUB_DISABLE_RECOVERY="true"

                # Uncomment to get a beep at grub start
                #GRUB_INIT_TUNE="480 440 1"

        - name  : Install cpufrequtils
          become: true
          shell:  |
                sudo apt-get install cpufrequtils -y
                sudo apt-get install i7z -y

        - name  : Generate new cpufrequtils file
          copy:
            dest: "/etc/default/cpufrequtils"
            content: |
                GOVERNOR="performance"

        - name  : Update grub
          shell: | 
             update-grub
             sudo update-rc.d ondemand disable
             sudo /etc/init.d/cpufrequtils restart
