---
-   hosts: OAISim-with-free5gc
    become: yes
    remote_user: root
    vars:
        BASE_DIR_INSTALL: 'oaisim-lte'

        num_ues_init_database: '100'
        web_application_access_port: '3000'
        init_free5gc_elements_simulation: 'false'
        start_webapp: 'true'
        deploy_oaisim: 'true'
        deploy_free5gc: 'true'
        docker_custom_subnet_network: '192.188.2.0/24'
        docker_custom_network_name: 'free5gc'
        ip_address_AMF: '192.188.2.2'
        ip_address_SMF: '192.188.2.3'
        ip_address_HSS: '192.188.2.4'
        ip_address_PCRF: '192.188.2.5'
        ip_address_UPF: '192.188.2.6'
        ip_address_MONGO_DB: '192.188.2.100'
        ip_address_WEB_UI: '192.188.2.101'
        ip_address_OAISIM_ENB: '192.188.2.253'
        ip_address_OAISIM_UE: '192.188.2.254'
        free5gc_st1_image_name: 'laboraufg/free5gc-st1'
        free5gc_webui_image_name: 'laboraufg/webui-free5gc'
        free5gc_mongodb_image_name: 'laboraufg/mongodb-free5gc'
        oaisim_enb_image_name: 'laboraufg/enb-openairsim'
        oaisim_ue_image_name: 'laboraufg/ue-openairsim'
        UE_container_name: 'ue'
        UE_folder_name_container_name: '/root/ue/'
        ENB_folder_name_container_name: '/root/enb/'
        ENB_container_name: 'enb'
        AMF_container_name: 'amf'
        SMF_container_name: 'smf'
        HSS_container_name: 'hss'
        PCRF_container_name: 'pcrf'
        UPF_container_name: 'upf'
        MONGO_DB_container_name: 'mongodb-svc'
        WEB_UI_container_name: 'webui'
        clear_file_instalation: 'true'
        HPLMN : "20893"
        default_username_WEBUI : "admin"
        default_password_WEBUI : "1423"
        enb_gumei_mcc_auth_param: '208'
        enb_gumei_mnc_auth_param: '93'
        log_level_tracer_free5gc: '5'
        path_workspace_free5gc: '/root/free5gc-stage-1'
        
        OPC : "e734f8734007d6c5ce7a0508809e7e9c"
        user_equiments:
            - { ue_id: UE0 ,   msin: '0000000001' }
            - { ue_id: UE1 ,   msin: '0000000002' }
            - { ue_id: UE2 ,   msin: '0000000003' }
            - { ue_id: UE3 ,   msin: '0000000004' }
            - { ue_id: UE4 ,   msin: '0000000005' }
            - { ue_id: UE5 ,   msin: '0000000006' }
            - { ue_id: UE6 ,   msin: '0000000007' }
    tasks:
        - name: Environment validation!
          assert:
            that:
              - ansible_memtotal_mb >= 1024
            msg: "Minimum memory requirements in the deployment environment is 4GB! Operation failed!"

        - name : Git clone openair-cn 
          shell: git clone https://github.com/OPENAIRINTERFACE/openair-cn/tree/v0.5.0
          args:
              chdir: "{{ BASE_DIR_INSTALL }}"