---
-   hosts: 127.0.0.1
    connection: local
    become: yes
    remote_user: root
    vars:
        BASE_DIR_INSTALL: '/root/oaisim-4g-install'
        clear_file_instalation: 'true'
        
        user_equiments:
            - { ue_id: UE0 ,   msin: '0000000001' }
            - { ue_id: UE1 ,   msin: '0000000002' }
            - { ue_id: UE2 ,   msin: '0000000003' }
            - { ue_id: UE3 ,   msin: '0000000004' }
            - { ue_id: UE4 ,   msin: '0000000005' }
            - { ue_id: UE5 ,   msin: '0000000006' }
            - { ue_id: UE6 ,   msin: '0000000007' }
    tasks:
        - name: Environment validation!
          assert:
            that:
              - ansible_memtotal_mb >= 1024
            msg: "Minimum memory requirements in the deployment environment is 4GB! Operation failed!"

        - name  : Remove old instalation
          shell :  |
                sudo rm -rf {{ BASE_DIR_INSTALL }}

        - name  : Create dir instalation
          file  :
            path: "{{ BASE_DIR_INSTALL }}"
            state: directory

        - name  : Clone openair-cn repository
          shell : git clone https://github.com/OPENAIRINTERFACE/openair-cn.git
          args  :
              chdir: "{{ BASE_DIR_INSTALL }}"

        - name : Build hss -i -F -v
          shell: ./build_hss -i -F -v
          args:
              chdir: "{{ BASE_DIR_INSTALL }}/openair-cn/scripts/"