---
-   hosts: oaisim-enB
    become: yes
    remote_user: root
    vars:
        COPY_RIGHT: 'ciromacedo@gmail.com'
    tasks:
        - name : Remove all old implantation
          become: yes
          ignore_errors: yes
          shell:  |
              git clone --branch v1.0.0 https://gitlab.eurecom.fr/oai/openairinterface5g/ 
 