---
-   hosts: oaisim-enB
    become: yes
    remote_user: root
    vars:
        COPY_RIGHT: 'ciromacedo@gmail.com'
    tasks:
        - name : Remove all old implantation
          become: true
          ignore_errors: true
          shell:  |
                sudo rm -rf ansible_enB

        - name : Create Directory
          become: true
          shell:  |
                sudo mkdir ansible_enB

        - name : Install OpenAirInteface
          become: true
          shell:  git clone --branch v1.0.0 https://gitlab.eurecom.fr/oai/openairinterface5g/ 
          args:
            chdir: ansible_enB/