---
-   hosts: free5g-CORE
    become: yes
    remote_user: root
    vars:
        COPY_RIGHT: 'ciromacedo@gmail.com'
        docker_custon_subnet_network: '192.188.2.0/24'
        docker_custon_network_name: 'free5gc'
        web_interface_port_access: '8080'
        BASE_DIR_INSTALL: 'free5gc-conf'
        ip_address_AMF: '192.188.2.2'
        ip_address_SMF: '192.188.2.3'
        ip_address_HSS: '192.188.2.4'
        ip_address_PCRF: '192.188.2.5'
        ip_address_UPF: '192.188.2.6'
        ip_address_MONGO_DB: '192.188.2.100'
        ip_address_WEB_UI: '192.188.2.101'
        
        AMF_container_name: 'amf'
        SMF_container_name: 'smf'
        HSS_container_name: 'hss'
        PCRF_container_name: 'pcrf'
        UPF_container_name: 'upf'
        MONGO_DB_container_name: 'mongodb'
        WEB_UI_container_name: 'webui'
    tasks:
        - name  : Generate certificates inside containers
          shell : |
                docker exec -ti {{ AMF_container_name }} bash 
                chmod u+x /root/free5gc-stage-1/support/freeDiameter/make_certs.sh
                /root/free5gc-stage-1/support/freeDiameter/make_certs.sh /root/free5gc-stage-1/support/freeDiameter/
                cd /root/free5gc-stage-1 && make install && exit




